### PR TITLE
Add support of GitLab source links

### PR DESCRIPTION
**Pull request by lockie**
Hello!
This small PR adds support for Gitlab source links like the one existing for Github.

### CODE REVIEW

**Comment by Shinmera** [comment]
Looks good, thanks!

Makes me wonder though if we could somehow devise a more general solution for self-hosted instances of gitlab, gitea, etc.

**Comment by lockie** [comment]
You're welcome!

> Makes me wonder though if we could somehow devise a more general solution for self-hosted instances

That will require to automatically determine that some website in fact is e.g. self-hosted GitLab instance. Sounds too hard for me :)

**Comment by Shinmera** [comment]
I can see two approaches: somehow setting that info in staple.ext.lisp, or probing it by sending a request, which I don't like.

**Comment by lockie** [comment]
Yeah, the latter sounds fragile. Maybe it makes sense to add some sort of extra configuration parameter to `staple:generate`, but the source link includes two parts - URL itself and the line number hash (`#L42`). Perhaps a plain format string, like
```lisp
(staple:generate
  :staple
  :source-link-format "https://github.com/Shinmera/staple/blob/master/~a~@[#L~a~]"
  ; ...
)
```
?.. (Just thinking out loud tho)

**Pull request merged**
